apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: CLUSTER_ID
    machine.openshift.io/cluster-api-machine-role: workerocs
    machine.openshift.io/cluster-api-machine-type: workerocs
  name: CLUSTER_ID-workerocs-AWS_ZONE
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: CLUSTER_ID
      machine.openshift.io/cluster-api-machineset: CLUSTER_ID-workerocs-AWS_ZONE
  template:
    metadata:
      creationTimestamp: null
      labels:
        machine.openshift.io/cluster-api-cluster: CLUSTER_ID
        machine.openshift.io/cluster-api-machine-role: workerocs
        machine.openshift.io/cluster-api-machine-type: workerocs
        machine.openshift.io/cluster-api-machineset: CLUSTER_ID-workerocs-AWS_ZONE
    spec:
      metadata:
        creationTimestamp: null
        labels:
          role: storage-node
          node-role.kubernetes.io/worker: ""
      providerSpec:
        value:
          ami:
            id: AWS_COREOS_AMI
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              iops: 0
              volumeSize: 120
              volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: CLUSTER_ID-worker-profile
          instanceType: m4.4xlarge
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: AWS_ZONE
            region: AWS_REGION
          publicIp: null
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - CLUSTER_ID-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - CLUSTER_ID-private-AWS_ZONE
          tags:
          - name: kubernetes.io/cluster/CLUSTER_ID
            value: owned
          userDataSecret:
            name: worker-user-data
      versions:
        kubelet: ""